definitions:
  models.Image:
    properties:
      title:
        type: string
      url:
        type: string
    required:
    - title
    - url
    type: object
  models.LGTM:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  models.News:
    properties:
      content:
        type: string
      date:
        type: string
      title:
        type: string
    type: object
  models.Report:
    properties:
      created_at:
        type: string
      id:
        type: string
      lgtm_id:
        type: string
      text:
        type: string
      type:
        $ref: '#/definitions/models.ReportType'
    type: object
  models.ReportType:
    enum:
    - illegal
    - inappropriate
    - other
    type: string
    x-enum-varnames:
    - ReportTypeIllegal
    - ReportTypeInappropriate
    - ReportTypeOther
  service.ErrCode:
    enum:
    - BAD_REQUEST
    - UNSUPPORTED_IMAGE_FORMAT
    - FAILED_TO_GET_IMAGE
    - NOT_FOUND
    - RATE_LIMIT_REACHED
    - INTERNAL_SERVER_ERROR
    type: string
    x-enum-varnames:
    - ErrCodeBadRequest
    - ErrCodeUnsupportedImageFormat
    - ErrCodeFailedToGetImage
    - ErrCodeNotFound
    - ErrCodeRateLimitReached
    - ErrCodeInternalServerError
  service.ErrorResponse:
    properties:
      code:
        $ref: '#/definitions/service.ErrCode'
    required:
    - code
    type: object
  service.createLGTMInput:
    properties:
      base64:
        type: string
      options:
        $ref: '#/definitions/service.createLGTMOptions'
      url:
        type: string
    type: object
  service.createLGTMOptions:
    properties:
      textColor:
        type: string
    type: object
  service.createReportInput:
    properties:
      lgtm_id:
        type: string
      text:
        type: string
      type:
        $ref: '#/definitions/models.ReportType'
    required:
    - lgtm_id
    - text
    - type
    type: object
info:
  contact: {}
paths:
  /v1/images:
    get:
      parameters:
      - description: query
        in: query
        name: q
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Image'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorResponse'
  /v1/lgtms:
    get:
      parameters:
      - description: limit
        in: query
        name: limit
        type: integer
      - description: after
        in: query
        name: after
        type: string
      - description: random
        in: query
        name: random
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.LGTM'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorResponse'
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service.createLGTMInput'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.LGTM'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorResponse'
  /v1/news:
    get:
      parameters:
      - description: locale
        in: query
        name: locale
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.News'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorResponse'
  /v1/reports:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service.createReportInput'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Report'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorResponse'
swagger: "2.0"
