version: "3.8"

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - ./localstack/ready.d:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
