service: lgtmgen-backend
frameworkVersion: "3"

custom:
  prefix: lgtmgen-${self:provider.stage}

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, "dev"}
  apiName: ${self:custom.prefix}
  ecr:
    images:
      api:
        path: ./
        file: ./dockerfiles/api/Dockerfile
        cacheFrom:
          - ${aws:accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/serverless-lgtmgen-backend-${self:provider.stage}:api
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::Join:
                - ":"
                - - arn:aws:dynamodb
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - table/${self:custom.prefix}-*
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - ${self:custom.prefix}-images
            - Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - ${self:custom.prefix}-images
                  - /*
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            Fn::Join:
              - ":"
              - - arn:aws:sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${self:custom.prefix}-*

  environment:
    STAGE: ${self:provider.stage}
    # Slack
    SLACK_OAUTH_TOKEN: ${env:SLACK_OAUTH_TOKEN}
    # DynamoDB Table
    DYNAMODB_TABLE_LGTMS: ${env:DYNAMODB_TABLE_LGTMS}
    DYNAMODB_TABLE_REPORTS: ${env:DYNAMODB_TABLE_REPORTS}
    # S3 Bucket
    S3_BUCKET_IMAGES: ${env:S3_BUCKET_IMAGES}
    # SQS Queue
    SQS_QUEUE_NOTIFICATIONS: ${env:SQS_QUEUE_NOTIFICATIONS}
    SQS_QUEUE_URL_NOTIFICATIONS: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${env:SQS_QUEUE_NOTIFICATIONS}

package:
  individually: true

functions:
  api:
    image:
      name: api
      command: [serve, --lambda]
    timeout: 30 # s
    events:
      - http:
          method: ANY
          path: "/{any+}"
  notify:
    image:
      name: api
      command: [notify, --lambda]
    timeout: 30 # s
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - NotificationsQueue
              - Arn

resources:
  Resources:
    LgtmsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_TABLE_LGTMS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: index_by_status
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    ReportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_TABLE_REPORTS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    NotificationsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${env:SQS_QUEUE_NOTIFICATIONS}
