import { i18n } from "@/lib/i18n";
import "./global.css";
import "@fontsource/archivo-black";
import type { Metadata } from "next";
import Link from "next/link";
import Providers from "@/providers/Providers";
import { AiOutlineGithub } from "react-icons/ai";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params: { locale },
  children,
}: {
  params: { locale: string };
  children: React.ReactNode;
}) {
  const t = i18n(locale);

  return (
    <html lang={locale}>
      <body className="bg-primary-light text-gray-600">
        <header className="bg-primary-main px-4 py-2 shadow">
          <h1
            className="text-3xl text-white"
            style={{ fontFamily: "Archivo Black" }}
          >
            <Link href={`/${locale}`}>{t.app}</Link>
          </h1>
        </header>

        <Providers locale={locale}>
          <main className="container mx-auto p-4 py-8">{children}</main>
        </Providers>

        <footer className="flex flex-col items-center gap-4">
          <ul className="flex flex-col items-center justify-center gap-2">
            <li>
              <a
                href="https://github.com/koki-develop/lgtmgen"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiOutlineGithub size={30} />
              </a>
            </li>
            <li>
              <Link href={`/${locale}/privacy`}>{t.privacyPolicy}</Link>
            </li>
            <li>
              <Link href={`/${locale}/usage-precautions`}>
                {t.usagePrecautions}
              </Link>
            </li>
          </ul>

          <small>&copy; 2023 Koki Sato</small>
        </footer>
      </body>
    </html>
  );
}
