name: CD - backend

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:
      google-api-key:
        required: true
      slack-oauth-token:
        required: true
      sentry-auth-token:
        required: true

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: backend
    env:
      FRONTEND_ORIGIN: ${{ vars.FRONTEND_ORIGIN }}
      # Sentry
      SENTRY_AUTH_TOKEN: ${{ secrets.sentry-auth-token }}
      SENTRY_ORG: ${{ vars.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT_BACKEND }}
      SENTRY_DSN: ${{ vars.SENTRY_DSN_BACKEND }}
      # Google
      GOOGLE_API_KEY: ${{ secrets.google-api-key }}
      SEARCH_ENGINE_ID: ${{ vars.SEARCH_ENGINE_ID }}
      # Slack
      SLACK_OAUTH_TOKEN: ${{ secrets.slack-oauth-token }}
      IMAGES_BASE_URL: ${{ vars.IMAGES_BASE_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: backend/package.json
          cache: yarn
          cache-dependency-path: backend/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: aws-actions/amazon-ecr-login@v1
      - name: Deploy
        run: yarn run deploy --stage ${{ inputs.environment }}

      - name: Get version
        run: |
          VERSION="${{ inputs.version }}"
          echo "VERSION=${VERSION#refs/tags/backend/*}" >> $GITHUB_ENV
      - uses: getsentry/action-release@v1
        with:
          version: ${{ env.VERSION }}
          environment: ${{ inputs.environment }}
          ignore_empty: true
