name: CI - backend

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
      - uses: ./.github/actions/setup-imagemagick

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run: go build .

      - name: Test
        run: go test ./...
