name: CD - backend (dev)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  cd:
    uses: ./.github/workflows/_cd_backend.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      version: ${{ github.sha }}
    secrets:
      google-api-key: ${{ secrets.GOOGLE_API_KEY }}
      azure-api-key: ${{ secrets.AZURE_API_KEY }}
      slack-oauth-token: ${{ secrets.SLACK_OAUTH_TOKEN }}
      sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
