name: CD - frontend (dev)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cd:
    uses: ./.github/workflows/_cd_frontend.yml
    with:
      environment: dev
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
