name: CD - frontend (dev)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  cd:
    uses: ./.github/workflows/_cd_frontend.yml
    with:
      environment: dev
      version: ${{ github.sha }}
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
