name: CD - frontend (prd)

on:
  push:
    tags:
      - "frontend/v*"

jobs:
  cd:
    uses: ./.github/workflows/_cd_frontend.yml
    with:
      environment: prd
      version: ${{ github.ref }}
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      sentry-auth-token: ${{ secrets.sentry-auth-token }}
